version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - resident
    links:
      - resident

  resident:
    restart: always
    build:
      context: ./release
      dockerfile: Dockerfile.react.prod
    ports:
      - 5000:5000
      
    
